server:
  port: 8080
---
dataservice:
  url: http://127.0.0.1:8000
  endpoint:
    status: ${dataservice.url}/data/status
    event: ${dataservice.url}/data/event
    fixed: ${dataservice.url}/data/fixed
---
download.from.bucket: false
---
storage:
  metadata-all: json/metadata-all.json
  data-store: json/datastore.json
  versions: json/versions.json
---
bucket:
  projectId: ssb-team-microdata-staging
  bucketName: data-service-bucket-microdata-poc
  datastore: no_ssb_test
  files:
    metadata-all:
      downloadFile: ${bucket.datastore}/metadata/metadata-all__1_0_0.json
      destFile: metadata_files/metadata-all.json
    data-store:
      downloadFile: ${bucket.datastore}/metadata/datastore.json
      destFile: metadata_files/datastore.json
    versions:
      downloadFile: ${bucket.datastore}/metadata/versions.json
      destFile: metadata_files/versions.json
---
info:
  version: @APPLICATION_VERSION@
---
logging:
  level:
    'no':
      microdata:
        datastore: INFO
    org:
      apache:
        http:
          headers: INFO
          wire: INFO
---
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 8081
---
spring:
  application:
    name: @APPLICATION_NAME@
  boot:
    admin:
      url:
  main:
    banner-mode: 'off'
server:
  servlet:
    encoding:
      force: false
